### ISSUE TITLE
Hi I am currently trying to grade your Challenge.

### ISSUE THREAD

**Issue by walterjamesperry** [wwartick/challenge1#1]
Please do not make any more changes while I am grading your repo. The files and folder keep disappearing. 

Thank you. 

Central Grader Walter Perry

**Comment by wwartick** [comment]
I do apologize, after submitting I immediately noticed many things to fix,
I am putting in the final touches now, and it should be ready in the next
couple of minutes. Sorry again for the trouble,

William Wartick
